---
name: Setup Mojo
author: Yevhen Fabizhevskyi
description: This action sets up a magic CLI.
branding:
  icon: terminal
  color: gray-dark
inputs:
  force:
    description: |
      If "true" it installs magic even if it is already installed on a runner.
      Otherwise, skips installation.
    default: "false"
    required: false
outputs:
  installed:
    description: Whether magic was installed or not.
    value: "${{ steps.install-magic.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'Windows' }}
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh

    - name: Validate inputs
      id: validate-inputs
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./validate-inputs.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Install magic
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-magic
      run: ./install-magic.sh
      shell: bash
      working-directory: "${{ github.action_path }}/src"

    - name: Print version
      run: magic --version
      shell: sh
